version: '3.8'

services:
  medical-ai-system:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./data:/app/data
      - ./weights:/app/weights
      - ./results:/app/results
    environment:
      - DEVICE=${DEVICE:-cuda}
      - OPENAI_API_KEY=${OPENAI_API_KEY}
    ports:
      - "8000:8000"
    restart: unless-stopped
    command: python -m cli serve --host 0.0.0.0 --port 8000 --device ${DEVICE:-cuda}
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]
        limits:
          memory: 16G
  
  database:
    image: mongo:latest
    volumes:
      - mongodb_data:/data/db
    ports:
      - "27017:27017"
    restart: unless-stopped
    environment:
      - MONGO_INITDB_ROOT_USERNAME=${MONGO_USERNAME:-medical_admin}
      - MONGO_INITDB_ROOT_PASSWORD=${MONGO_PASSWORD:-secure_password}
    
  vector-db:
    image: qdrant/qdrant:latest
    volumes:
      - qdrant_data:/qdrant/storage
    ports:
      - "6333:6333"
      - "6334:6334"
    restart: unless-stopped

volumes:
  mongodb_data:
  qdrant_data: 